<a href="https://colab.research.google.com/github/RojaCM/DEEP-LEARNING-/blob/main/PyTorch%20basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PYTORCH

In [1]:
import numpy as np
import torch

In [2]:
a=np.array(1)

In [4]:
b=torch.tensor(1)

In [5]:
a

array(1)

In [6]:
b

tensor(1)

In [7]:
type(a)

numpy.ndarray

In [8]:
type(b)

torch.Tensor

Mathematical operations

In [11]:
c=np.array(2)

In [12]:
a+c

3

In [13]:
a-c

-1

In [14]:
d=torch.tensor(5)

In [15]:
b+d

tensor(6)

In [20]:
a1=np.random.randn(3,3)
a1

array([[ 1.0841792 , -0.25299436,  1.01465532],
       [ 1.19243615,  0.03364076,  0.12519277],
       [-0.96045486, -1.02552703, -0.83902501]])

In [21]:
b1=np.random.randn(3,3)

In [22]:
np.add(a1,b1)

array([[ 2.97435445, -1.54009267,  0.28769181],
       [ 1.11552572, -1.85483199, -1.68687401],
       [-1.08930393, -1.53479489, -2.2446926 ]])

In [23]:
np.subtract(a1,b1)

array([[-0.80599605,  1.03410396,  1.74161883],
       [ 1.26934659,  1.9221135 ,  1.93725955],
       [-0.83160579, -0.51625916,  0.56664258]])

In [24]:
np.dot(a1,b1)

array([[ 1.93800921, -1.43440362, -1.75598415],
       [ 2.23519501, -1.66206887, -1.10379629],
       [-1.62844668,  3.60016815,  3.73592936]])

In [25]:
np.divide(a1,b1)

array([[  0.5735866 ,   0.1965618 ,  -1.3957445 ],
       [-15.50421766,  -0.01781374,  -0.06908839],
       [  7.454108  ,   2.01372813,   0.59688721]])

In [27]:
np.transpose(a1)

array([[ 1.0841792 ,  1.19243615, -0.96045486],
       [-0.25299436,  0.03364076, -1.02552703],
       [ 1.01465532,  0.12519277, -0.83902501]])

In [29]:
torch.manual_seed(42)

d1=torch.randn(3,3)

In [30]:
d2=torch.randn(3,3)

In [31]:
torch.add(d1,d2)

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])

In [32]:
torch.sub(d1,d2)

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])

In [33]:
torch.mm(d1,d2)

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])

In [34]:
torch.div(d1,d2)

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])

In [35]:
torch.t(d1)

tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])

#Concatenating Tensors

In [38]:
w=torch.tensor([[1,2],[3,4]])

In [40]:
x=torch.tensor([[5,6],[7,8]])

In [42]:
torch.cat((w,x))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [43]:
torch.cat((w,x),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

#Reshaping Tensors

In [45]:
torch.manual_seed(42)
y=torch.randn(2,4)

In [46]:
y

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])

In [47]:
y.reshape(1,8)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380]])

In [48]:
a=np.array([[6,7],[8,9]])

In [49]:
torch.from_numpy(a)

tensor([[6, 7],
        [8, 9]])

Common PyTorch Modules
Autograd Module

PyTorch uses a technique called automatic differentiation. It records all the operations that we are performing and replays it backward to compute gradients. This technique helps us to save time on each epoch as we are calculating the gradients on the forward pass itself.

In [50]:
p=torch.ones(2,2,requires_grad=True)

In [51]:
q=p+5

In [52]:
c=q.mean()

In [54]:
c.backward()

In [55]:
q

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)

In [58]:
p.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

The autograd module helps us to compute the gradients in the forward pass itself which saves a lot of computation time of an epoch.

#OPTIM MODULE
IT HAS PREWRITTEN CODES FOR THE OPTIMIZERS THAT ARE USED WHILE BUILDING THE NEURAL NETWORK.WE JUST HAVE TO IMPORT THEM AND THEN THEY CAN BE USED TO BUILD MODELS.

# importing the optim module
from torch import optim

# adam
## adam = optim.Adam(model.parameters(), lr=learning_rate)

# sgd
## SGD = optim.SGD(model.parameters(), lr=learning_rate)

Above are the examples to get the ADAM and SGD optimizers. Most of the commonly used optimizers are supported in PyTorch and hence we do not have to write them from scratch. Some of them are:

SGD
Adam
Adadelta
Adagrad
AdamW
SparseAdam
Adamax
ASGD (Averaged Stochastic Gradient Descent)
RMSprop
Rprop (resilient backpropagation)

Building a Neural Network from Scratch in PyTorch

In [60]:
#input tensor
x=torch.tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

In [61]:
y=torch.tensor([[1],[1],[0]])

In [62]:
x

tensor([[1, 0, 1, 0],
        [1, 0, 1, 1],
        [0, 1, 0, 1]])

In [63]:
y

tensor([[1],
        [1],
        [0]])

Next, we will define the sigmoid function which will act as the activation function and the derivative of the sigmoid function which will help us in the backpropagation step:

In [64]:
#sigmoid function

def sigmoid_fun(x):
  return 1/(1+torch.exp(-x))

In [66]:
def derivative_sig_fun(x):
  return sigmoid(x) * (1-sigmoid(x))

In [69]:
x.shape

torch.Size([3, 4])

Next, initialize the parameters for our model including the number of epochs, learning rate, weights, biases, etc.:

In [70]:
epochs=50
learning_rate=0.1
input_layers=x.shape[1]
hidden_layers=3
output_layers=1

In [81]:
#weight and bias initialization
wh=torch.randn(input_layers, hidden_layers)
bh=torch.randn(1, hidden_layers)
wout=torch.randn(hidden_layers, output_layers)
bout=torch.randn(1, output_layers)

In [83]:
for i in range(epochs):
    #Forward Propogation
    hidden_layer_input1 = torch.mm(x, wh)
    hidden_layer_input = hidden_layer_input1 + bh
    hidden_layer_activations = sigmoid(hidden_layer_input)

    output_layer_input1 = torch.mm(hidden_layer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)

     #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = torch.mm(d_output, wout.t())
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += torch.mm(hidden_layer_activations.t(), d_output) *lr
    bout += d_output.sum() *lr
    wh += torch.mm(X.t(), d_hiddenlayer) *lr
    bh += d_output.sum() *lr

RuntimeError: ignored